# Creation of Array (1D,2D and Multidimennsional array)

In [1]:
#Exp no. : 5

In [2]:
#Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [3]:
#Name : Riya M.Bhattad
#Roll no. : 14
#Section : A 
#Subject : PE-I
#Date : 04-10-24

In [4]:
import numpy as np

In [5]:
arr1=np.array([10,20,30,40,50])

In [6]:
arr1



array([10, 20, 30, 40, 50])

In [7]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [8]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [9]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [10]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])